name: Build Linux Image

on:
  push:
    branches: [ ci/cd ]
    paths:
      - 'Dockerfile'
  pull_request:
    branches: [ ci/cd ]
    paths:
      - 'Dockerfile'

jobs:
  build-linux-image:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Lowercase Repository Name
        id: repo_name
        run: echo "REPO_NAME_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"
      - name: Build and Push Linux Image
        run: |
          docker build -f Dockerfile -t ghcr.io/${REPO_NAME_LOWER}/ci-image-linux:latest .
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${REPO_NAME_LOWER}/ci-image-linux:latest
