name: Build Docker Images

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile'

jobs:
  build-linux-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Build and Push Linux Image
        run: |
          docker build -f Dockerfile -t ghcr.io/${{ REPO }}/ci-image-linux:latest .
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ REPO }}/ci-image-linux:latest
