name: CI

on:
  push:
    branches: [ ci/cd ]
  pull_request:
    branches: [ ci/cd ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Windows Image
        run: |
          docker build -f Dockerfile.windows -t ci-image-windows:latest .
      - name: Test Build
        shell: powershell
        run: |
          docker run --rm -v ${PWD}:C:\app ci-image-windows:latest powershell -Command "mkdir build; cd build; cmake -G 'Visual Studio 17 2022' ..; cmake --build . --config Release"

  build-linux:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository }}/ci-image-linux:latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make -j$(nproc)

