name: CI

on:
  push:
    branches: [ ci/cd ]
  pull_request:
    branches: [ ci/cd ]

jobs:
  build-windows:
    runs-on: windows-latest
    container:
      image: ghcr.io/${{ github.repository }}/ci-image-windows:latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Configure CMake
        shell: powershell
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" ..
      - name: Build
        shell: powershell
        run: |
          cd build
          cmake --build -j$(nproc) .

  build-linux:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository }}/ci-image-linux:latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          cd build
          make -j$(nproc)

